spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    url: jdbc:h2:tcp://localhost/~/jpashop #띄어쓰기 4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      #ddl-auto: none #초기화 하지 않겠다
      ddl-auto: create
    properties:
      hibernate:
          #show_sql: true
          format_sql: true
          default_batch_fetch_size: 100
    #open-in-view: false


logging.level:
  org.hibernate.SQL: debug # logger를 통해 하이버네이트 실행SQL
  #org.hibernate.show_sql : debug # System.out에 하이버네이트 실행SQL
  org.hibernate.type: trace

